import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { requireRole, handle, ApiError } from '@/lib/api-helpers';
import { MANAGER_ROLES } from '@/lib/auth';
import { getAuditTrail } from '@/lib/audit-logger';
import { getExpiryReport } from '@/lib/expiry-checker';
import { checkScheduleMCompliance } from '@/lib/schedule-m';
import { ROLE_LABELS } from '@/lib/types';
import { formatDate, formatDateTime, daysUntil } from '@/lib/utils';

const EXPORT_TYPES = ['training', 'capa', 'audit', 'requalification', 'schedule-m'] as const;
type ExportType = (typeof EXPORT_TYPES)[number];

interface Dataset {
  columns: string[];
  rows: Record<string, string>[];
}

interface DateRange {
  from?: Date;
  to?: Date;
}

function csvCell(value: string): string {
  if (/[",\n\r]/.test(value)) return `"${value.replace(/"/g, '""')}"`;
  return value;
}

function toCsv(dataset: Dataset): string {
  const lines = [dataset.columns.map(csvCell).join(',')];
  for (const row of dataset.rows) {
    lines.push(dataset.columns.map((c) => csvCell(row[c] ?? '')).join(','));
  }
  return lines.join('\r\n');
}

function rangeFilter(range: DateRange): { gte?: Date; lte?: Date } | undefined {
  if (!range.from && !range.to) return undefined;
  const f: { gte?: Date; lte?: Date } = {};
  if (range.from) f.gte = range.from;
  if (range.to) f.lte = range.to;
  return f;
}

async function buildDataset(type: ExportType, companyId: string, range: DateRange): Promise<Dataset> {
  const created = rangeFilter(range);
  switch (type) {
    case 'training': {
      const records = await prisma.trainingRecord.findMany({
        where: { user: { companyId }, ...(created ? { createdAt: created } : {}) },
        orderBy: { createdAt: 'desc' },
        include: {
          user: { select: { name: true, department: true } },
          machine: { select: { name: true } },
          module: { select: { title: true } },
        },
      });
      const columns = [
        'User', 'Department', 'Machine', 'Module', 'Status', 'Score',
        'Attempts', 'Requalification', 'Started', 'Completed', 'Expires', 'Signed At',
      ];
      return {
        columns,
        rows: records.map((r) => ({
          User: r.user.name,
          Department: r.user.department ?? '',
          Machine: r.machine.name,
          Module: r.module?.title ?? 'Requalification',
          Status: r.status,
          Score: r.score === null ? '' : String(r.score),
          Attempts: String(r.attempts),
          Requalification: r.isRequalification ? 'Yes' : 'No',
          Started: r.startedAt ? formatDateTime(r.startedAt) : '',
          Completed: r.completedAt ? formatDateTime(r.completedAt) : '',
          Expires: r.expiresAt ? formatDate(r.expiresAt) : '',
          'Signed At': r.signedAt ? formatDateTime(r.signedAt) : '',
        })),
      };
    }
    case 'capa': {
      const records = await prisma.cAPA.findMany({
        where: { companyId, ...(created ? { createdAt: created } : {}) },
        orderBy: { createdAt: 'desc' },
        include: {
          owner: { select: { name: true } },
          machine: { select: { name: true } },
        },
      });
      const columns = [
        'CAPA Number', 'Title', 'Severity', 'Status', 'Deviation Type', 'Owner',
        'Machine', 'Due Date', 'Closed At', 'Auto Generated', 'Trigger', 'Created',
      ];
      return {
        columns,
        rows: records.map((c) => ({
          'CAPA Number': c.capaNumber,
          Title: c.title,
          Severity: c.severity,
          Status: c.status,
          'Deviation Type': c.deviationType,
          Owner: c.owner.name,
          Machine: c.machine?.name ?? '',
          'Due Date': formatDate(c.dueDate),
          'Closed At': c.closedAt ? formatDate(c.closedAt) : '',
          'Auto Generated': c.autoGenerated ? 'Yes' : 'No',
          Trigger: c.triggerReason ?? '',
          Created: formatDate(c.createdAt),
        })),
      };
    }
    case 'audit': {
      const rows = await getAuditTrail({ companyId, from: range.from, to: range.to, take: 500 });
      const columns = [
        'Timestamp', 'User', 'Role', 'Action', 'Entity Type', 'Entity ID',
        'Old Value', 'New Value', 'Change Reason', 'IP Address',
      ];
      return {
        columns,
        rows: rows.map((r) => ({
          Timestamp: formatDateTime(r.timestamp),
          User: r.user?.name ?? 'System',
          Role: r.user ? ROLE_LABELS[r.user.role] : '',
          Action: r.action,
          'Entity Type': r.entityType,
          'Entity ID': r.entityId,
          'Old Value': r.oldValue === null ? '' : JSON.stringify(r.oldValue),
          'New Value': r.newValue === null ? '' : JSON.stringify(r.newValue),
          'Change Reason': r.changeReason ?? '',
          'IP Address': r.ipAddress ?? '',
        })),
      };
    }
    case 'requalification': {
      const report = await getExpiryReport(companyId);
      const columns = ['User', 'Department', 'Machine', 'Status', 'Expires', 'Days Remaining'];
      return {
        columns,
        rows: report.records.map((r) => {
          const d = daysUntil(r.expiresAt);
          return {
            User: r.user.name,
            Department: r.user.department ?? '',
            Machine: r.machine.name,
            Status: r.status,
            Expires: r.expiresAt ? formatDate(r.expiresAt) : '',
            'Days Remaining': d === null ? '' : String(d),
          };
        }),
      };
    }
    case 'schedule-m': {
      const report = await checkScheduleMCompliance(companyId);
      const columns = ['Chapter', 'Title', 'Requirement', 'Status', 'Evidence'];
      return {
        columns,
        rows: report.items.map((i) => ({
          Chapter: i.chapter,
          Title: i.title,
          Requirement: i.requirement,
          Status: i.status,
          Evidence: i.evidence,
        })),
      };
    }
    default: {
      const exhaustive: never = type;
      throw new ApiError(`Unsupported export type: ${String(exhaustive)}`, 422);
    }
  }
}

/**
 * GET /api/reports/export
 * ?type=training|capa|audit|requalification|schedule-m &format=csv|json
 * Company-scoped, managers only. CSV downloads as an attachment.
 */
export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const typeParam = searchParams.get('type');
  const format = searchParams.get('format') === 'json' ? 'json' : 'csv';

  if (!typeParam || !EXPORT_TYPES.includes(typeParam as ExportType)) {
    return NextResponse.json(
      { error: `Invalid type. Expected one of: ${EXPORT_TYPES.join(', ')}` },
      { status: 422 }
    );
  }
  const type = typeParam as ExportType;

  const fromRaw = searchParams.get('from');
  const toRaw = searchParams.get('to');
  const fromDate = fromRaw ? new Date(fromRaw) : undefined;
  const toDate = toRaw ? new Date(toRaw) : undefined;
  const range: DateRange = {
    from: fromDate && !isNaN(fromDate.getTime()) ? fromDate : undefined,
    to: toDate && !isNaN(toDate.getTime()) ? toDate : undefined,
  };

  if (format === 'json') {
    return handle(async () => {
      const manager = await requireRole(MANAGER_ROLES);
      const dataset = await buildDataset(type, manager.companyId, range);
      return { type, columns: dataset.columns, rows: dataset.rows };
    });
  }

  // CSV path — needs a raw Response, so guard auth explicitly.
  let manager;
  try {
    manager = await requireRole(MANAGER_ROLES);
  } catch (err) {
    const status = err instanceof ApiError ? err.status : 500;
    const message = err instanceof Error ? err.message : 'Unauthorized';
    return NextResponse.json({ error: message }, { status });
  }

  const dataset = await buildDataset(type, manager.companyId, range);
  const csv = toCsv(dataset);
  const filename = `${type}-export-${new Date().toISOString().slice(0, 10)}.csv`;
  return new NextResponse(csv, {
    status: 200,
    headers: {
      'Content-Type': 'text/csv; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  });
}
