'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { ArrowLeft, Bot, Loader2, Pencil } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { useToast } from '@/components/ui/use-toast';
import { apiFetch } from '@/lib/client';
import { formatDate } from '@/lib/utils';
import {
  SEVERITY_BADGE_CLASS,
  CAPA_STATUS_OPTIONS,
  type CAPASeverityValue,
  type CAPAStatusValue,
} from '@/components/capa/CAPACard';
import { CAPAWorkflow } from '@/components/capa/CAPAWorkflow';
import { CAPATimeline, type CAPAAuditLog } from '@/components/capa/CAPATimeline';
import { CAPAEffectiveness } from '@/components/capa/CAPAEffectiveness';

interface TrainingRecordLink {
  id: string;
  status: string;
  completedAt: string | null;
  expiresAt: string | null;
  user: { id: string; name: string };
  machine: { id: string; name: string };
}

interface CAPADetail {
  id: string;
  capaNumber: string;
  title: string;
  description: string;
  severity: CAPASeverityValue;
  status: CAPAStatusValue;
  deviationType: string;
  rootCause: string | null;
  immediateAction: string | null;
  preventiveAction: string | null;
  effectivenessCheck: string | null;
  effectivenessDate: string | null;
  dueDate: string;
  closedAt: string | null;
  createdAt: string;
  autoGenerated: boolean;
  triggerReason: string | null;
  ownerId: string;
  owner: { id: string; name: string; email: string; role: string };
  machine: { id: string; name: string } | null;
  auditLogs: CAPAAuditLog[];
  trainingRecords: TrainingRecordLink[];
}

interface DetailResponse {
  capa: CAPADetail;
  canManage: boolean;
}

export default function CAPADetailPage() {
  const params = useParams<{ id: string }>();
  const id = params.id;
  const { toast } = useToast();

  const [capa, setCapa] = useState<CAPADetail | null>(null);
  const [canManage, setCanManage] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await apiFetch<DetailResponse>(`/api/capa/${id}`);
      setCapa(res.capa);
      setCanManage(res.canManage);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load CAPA');
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    void load();
  }, [load]);

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-8 w-40" />
        <div className="grid gap-6 lg:grid-cols-3">
          <Skeleton className="h-64 lg:col-span-2" />
          <Skeleton className="h-64" />
        </div>
      </div>
    );
  }

  if (error || !capa) {
    return (
      <Card>
        <CardContent className="flex flex-col items-center gap-3 py-16 text-center">
          <p className="text-sm text-muted-foreground">{error ?? 'CAPA not found.'}</p>
          <Button asChild variant="outline">
            <Link href="/capa">Back to CAPAs</Link>
          </Button>
        </CardContent>
      </Card>
    );
  }

  const statusLabel =
    CAPA_STATUS_OPTIONS.find((o) => o.value === capa.status)?.label ?? capa.status;

  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <Button asChild variant="ghost" size="sm" className="-ml-2">
          <Link href="/capa">
            <ArrowLeft className="h-4 w-4" /> Back to CAPAs
          </Link>
        </Button>
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="space-y-1">
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-sm font-semibold text-pharma-blue">{capa.capaNumber}</span>
              <Badge className={SEVERITY_BADGE_CLASS[capa.severity]}>{capa.severity}</Badge>
              <Badge variant="outline">{statusLabel}</Badge>
              {capa.autoGenerated && (
                <Badge variant="purple" className="gap-1">
                  <Bot className="h-3 w-3" /> Auto-generated
                </Badge>
              )}
            </div>
            <h1 className="text-2xl font-bold tracking-tight">{capa.title}</h1>
          </div>
          {canManage && <EditInvestigationDialog capa={capa} onSaved={load} />}
        </div>
      </div>

      {capa.autoGenerated && capa.triggerReason && (
        <Card className="border-pharma-purple/40 bg-pharma-purple/5">
          <CardContent className="flex items-center gap-3 py-4">
            <Bot className="h-5 w-5 text-pharma-purple" />
            <p className="text-sm">
              Auto-generated by trigger:{' '}
              <span className="font-medium">{capa.triggerReason.replace(/_/g, ' ')}</span>
            </p>
          </CardContent>
        </Card>
      )}

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="space-y-6 lg:col-span-2">
          <Card>
            <CardHeader>
              <CardTitle>Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <dl className="grid gap-4 sm:grid-cols-2">
                <Field label="Owner" value={`${capa.owner.name}`} sub={capa.owner.email} />
                <Field label="Machine" value={capa.machine?.name ?? '—'} />
                <Field label="Deviation Type" value={capa.deviationType.replace(/_/g, ' ')} />
                <Field label="Due Date" value={formatDate(capa.dueDate)} />
                <Field label="Created" value={formatDate(capa.createdAt)} />
                <Field label="Closed" value={capa.closedAt ? formatDate(capa.closedAt) : '—'} />
              </dl>
              <Section title="Description" body={capa.description} />
              <Section title="Immediate Action" body={capa.immediateAction} />
              <Section title="Root Cause" body={capa.rootCause} />
              <Section title="Preventive Action" body={capa.preventiveAction} />
            </CardContent>
          </Card>

          {capa.trainingRecords.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Linked Training Records</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                {capa.trainingRecords.map((r) => (
                  <div
                    key={r.id}
                    className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3 text-sm"
                  >
                    <div>
                      <p className="font-medium">{r.user.name}</p>
                      <p className="text-xs text-muted-foreground">{r.machine.name}</p>
                    </div>
                    <div className="flex items-center gap-3 text-xs text-muted-foreground">
                      <Badge variant="outline">{r.status.replace(/_/g, ' ')}</Badge>
                      {r.completedAt && <span>Completed {formatDate(r.completedAt)}</span>}
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          )}

          <CAPATimeline
            createdAt={capa.createdAt}
            createdBy={capa.autoGenerated ? 'System (auto-generated)' : null}
            auditLogs={capa.auditLogs}
          />
        </div>

        <div className="space-y-6">
          <CAPAWorkflow
            capaId={capa.id}
            status={capa.status}
            canManage={canManage}
            onChanged={() => void load()}
          />
          <CAPAEffectiveness
            status={capa.status}
            effectivenessCheck={capa.effectivenessCheck}
            effectivenessDate={capa.effectivenessDate}
            closedAt={capa.closedAt}
          />
        </div>
      </div>
    </div>
  );
}

function Field({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div>
      <dt className="text-xs uppercase tracking-wide text-muted-foreground">{label}</dt>
      <dd className="text-sm font-medium">{value}</dd>
      {sub && <dd className="text-xs text-muted-foreground">{sub}</dd>}
    </div>
  );
}

function Section({ title, body }: { title: string; body: string | null }) {
  return (
    <div className="space-y-1">
      <h3 className="text-sm font-semibold">{title}</h3>
      <p className="whitespace-pre-wrap text-sm text-muted-foreground">
        {body?.trim() ? body : '—'}
      </p>
    </div>
  );
}

function EditInvestigationDialog({
  capa,
  onSaved,
}: {
  capa: CAPADetail;
  onSaved: () => void;
}) {
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [immediateAction, setImmediateAction] = useState(capa.immediateAction ?? '');
  const [rootCause, setRootCause] = useState(capa.rootCause ?? '');
  const [preventiveAction, setPreventiveAction] = useState(capa.preventiveAction ?? '');
  const [dueDate, setDueDate] = useState(capa.dueDate.slice(0, 10));

  async function save() {
    setSaving(true);
    try {
      await apiFetch(`/api/capa/${capa.id}`, {
        method: 'PUT',
        body: JSON.stringify({
          immediateAction: immediateAction.trim() || null,
          rootCause: rootCause.trim() || null,
          preventiveAction: preventiveAction.trim() || null,
          dueDate: new Date(dueDate).toISOString(),
        }),
      });
      toast({ title: 'CAPA updated' });
      setOpen(false);
      onSaved();
    } catch (err) {
      toast({
        variant: 'destructive',
        title: 'Could not update CAPA',
        description: err instanceof Error ? err.message : 'Please retry.',
      });
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline">
          <Pencil className="h-4 w-4" /> Edit Investigation
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Edit Investigation</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="edit-due">Due Date</Label>
            <Input
              id="edit-due"
              type="date"
              value={dueDate}
              onChange={(e) => setDueDate(e.target.value)}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="edit-immediate">Immediate Action</Label>
            <Textarea
              id="edit-immediate"
              rows={2}
              value={immediateAction}
              onChange={(e) => setImmediateAction(e.target.value)}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="edit-root">Root Cause</Label>
            <Textarea
              id="edit-root"
              rows={3}
              value={rootCause}
              onChange={(e) => setRootCause(e.target.value)}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="edit-preventive">Preventive Action</Label>
            <Textarea
              id="edit-preventive"
              rows={3}
              value={preventiveAction}
              onChange={(e) => setPreventiveAction(e.target.value)}
            />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => setOpen(false)} disabled={saving}>
            Cancel
          </Button>
          <Button onClick={save} disabled={saving}>
            {saving && <Loader2 className="h-4 w-4 animate-spin" />} Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
