'use client';

import Link from 'next/link';
import { AlertTriangle, User as UserIcon, CalendarClock, Bot } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { cn, formatDate, daysUntil } from '@/lib/utils';

export type CAPASeverityValue = 'MINOR' | 'MAJOR' | 'CRITICAL';
export type CAPAStatusValue =
  | 'OPEN'
  | 'INVESTIGATION'
  | 'ACTION_TAKEN'
  | 'VERIFICATION'
  | 'CLOSED'
  | 'OVERDUE';

export interface CAPACardData {
  id: string;
  capaNumber: string;
  title: string;
  description: string;
  severity: CAPASeverityValue;
  status: CAPAStatusValue;
  deviationType: string;
  dueDate: string;
  closedAt: string | null;
  createdAt: string;
  autoGenerated: boolean;
  triggerReason: string | null;
  ownerId: string;
  ownerName: string;
  machineId: string | null;
  machineName: string | null;
}

export const CAPA_STATUS_OPTIONS: { value: CAPAStatusValue; label: string }[] = [
  { value: 'OPEN', label: 'Open' },
  { value: 'INVESTIGATION', label: 'Investigation' },
  { value: 'ACTION_TAKEN', label: 'Action Taken' },
  { value: 'VERIFICATION', label: 'Verification' },
  { value: 'CLOSED', label: 'Closed' },
  { value: 'OVERDUE', label: 'Overdue' },
];

export const SEVERITY_BADGE_CLASS: Record<CAPASeverityValue, string> = {
  MINOR: 'bg-capa-minor text-white border-transparent',
  MAJOR: 'bg-capa-major text-white border-transparent',
  CRITICAL: 'bg-capa-critical text-white border-transparent',
};

export function isCapaOverdue(capa: Pick<CAPACardData, 'dueDate' | 'status'>): boolean {
  if (capa.status === 'CLOSED') return false;
  return new Date(capa.dueDate).getTime() < Date.now();
}

interface CAPACardProps {
  capa: CAPACardData;
  canManage: boolean;
  busy?: boolean;
  onStatusChange?: (id: string, status: CAPAStatusValue) => void;
}

export function CAPACard({ capa, canManage, busy, onStatusChange }: CAPACardProps) {
  const overdue = isCapaOverdue(capa);
  const days = daysUntil(capa.dueDate);

  return (
    <Card
      className={cn(
        'p-3 space-y-2 shadow-sm transition-shadow hover:shadow-md',
        overdue && 'border-2 border-pharma-danger'
      )}
    >
      <div className="flex items-start justify-between gap-2">
        <Link
          href={`/capa/${capa.id}`}
          className="text-xs font-semibold text-pharma-blue hover:underline"
        >
          {capa.capaNumber}
        </Link>
        <Badge className={SEVERITY_BADGE_CLASS[capa.severity]}>{capa.severity}</Badge>
      </div>

      <Link href={`/capa/${capa.id}`} className="block">
        <p className="text-sm font-medium leading-snug line-clamp-2 hover:text-pharma-blue">
          {capa.title}
        </p>
      </Link>

      <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted-foreground">
        <span className="inline-flex items-center gap-1">
          <UserIcon className="h-3.5 w-3.5" />
          {capa.ownerName}
        </span>
        <span
          className={cn(
            'inline-flex items-center gap-1',
            overdue && 'font-semibold text-pharma-danger'
          )}
        >
          <CalendarClock className="h-3.5 w-3.5" />
          {formatDate(capa.dueDate)}
          {overdue && days !== null ? ` (${Math.abs(days)}d late)` : ''}
        </span>
      </div>

      {capa.machineName && (
        <p className="text-xs text-muted-foreground truncate">{capa.machineName}</p>
      )}

      <div className="flex items-center justify-between gap-2 pt-1">
        {capa.autoGenerated ? (
          <span className="inline-flex items-center gap-1 text-[11px] text-pharma-purple">
            <Bot className="h-3.5 w-3.5" /> Auto
          </span>
        ) : (
          <span />
        )}
        {overdue && (
          <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-pharma-danger">
            <AlertTriangle className="h-3.5 w-3.5" /> Overdue
          </span>
        )}
      </div>

      {canManage && onStatusChange ? (
        <Select
          value={capa.status}
          onValueChange={(v) => onStatusChange(capa.id, v as CAPAStatusValue)}
          disabled={busy}
        >
          <SelectTrigger className="h-8 text-xs">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {CAPA_STATUS_OPTIONS.map((o) => (
              <SelectItem key={o.value} value={o.value} className="text-xs">
                {o.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      ) : (
        <Badge variant="outline" className="text-[11px]">
          {CAPA_STATUS_OPTIONS.find((o) => o.value === capa.status)?.label ?? capa.status}
        </Badge>
      )}
    </Card>
  );
}
