import { prisma } from './prisma';
import type { CAPASeverity, CAPAStatus, DeviationType, Role } from '@prisma/client';
import type { CAPATrigger } from './types';
import { generateCAPANumber, addDays } from './utils';
import { logAction } from './audit-logger';
import { sendCAPAAssignment } from './email-service';

interface TriggerConfig {
  severity: CAPASeverity;
  deviationType: DeviationType;
  dueDays: number;
  titlePrefix: string;
}

const TRIGGER_MAP: Record<CAPATrigger, TriggerConfig> = {
  QUIZ_FAILED_3_TIMES: {
    severity: 'MINOR',
    deviationType: 'PERSONNEL',
    dueDays: 14,
    titlePrefix: 'Repeated quiz failure',
  },
  SIMULATION_SCORE_BELOW_50: {
    severity: 'MAJOR',
    deviationType: 'PROCESS_DEVIATION',
    dueDays: 7,
    titlePrefix: 'Low simulation competency',
  },
  OJT_FAILED: {
    severity: 'MAJOR',
    deviationType: 'PERSONNEL',
    dueDays: 7,
    titlePrefix: 'OJT assessment failed',
  },
  CERT_EXPIRED_30_DAYS: {
    severity: 'MINOR',
    deviationType: 'DOCUMENTATION_ERROR',
    dueDays: 14,
    titlePrefix: 'Certification expired > 30 days',
  },
  SIMULATION_CRITICAL_FAULT_WRONG: {
    severity: 'MAJOR',
    deviationType: 'EQUIPMENT_FAILURE',
    dueDays: 7,
    titlePrefix: 'Incorrect critical fault response',
  },
  BMR_CRITICAL_DEVIATION: {
    severity: 'CRITICAL',
    deviationType: 'PROCESS_DEVIATION',
    dueDays: 2,
    titlePrefix: 'Critical BMR deviation',
  },
};

const DUE_BY_SEVERITY: Record<CAPASeverity, number> = {
  MINOR: 14,
  MAJOR: 7,
  CRITICAL: 2,
};

async function nextCapaSeq(): Promise<number> {
  const today = new Date();
  const start = new Date(today.getFullYear(), today.getMonth(), today.getDate());
  const count = await prisma.cAPA.count({ where: { createdAt: { gte: start } } });
  return count + 1;
}

/** Find the Training Manager for a company (CAPA owner default). */
async function findOwner(companyId: string, department?: string | null): Promise<string | null> {
  const roles: Role[] = ['TRAINING_MANAGER', 'QA_OFFICER', 'ADMIN'];
  for (const role of roles) {
    const mgr = await prisma.user.findFirst({
      where: { companyId, role, ...(department ? { department } : {}) },
    });
    if (mgr) return mgr.id;
    const any = await prisma.user.findFirst({ where: { companyId, role } });
    if (any) return any.id;
  }
  const fallback = await prisma.user.findFirst({ where: { companyId } });
  return fallback?.id ?? null;
}

export interface CheckAndCreateInput {
  trigger: CAPATrigger;
  userId: string;
  companyId: string;
  machineId?: string | null;
  details: { description?: string; severityOverride?: CAPASeverity; trainingRecordId?: string };
}

export async function checkAndCreateCAPA(input: CheckAndCreateInput) {
  const cfg = TRIGGER_MAP[input.trigger];
  const severity = input.details.severityOverride ?? cfg.severity;
  const dueDays = DUE_BY_SEVERITY[severity] ?? cfg.dueDays;

  const ownerId = await findOwner(input.companyId);
  if (!ownerId) return null;

  const seq = await nextCapaSeq();
  const capaNumber = generateCAPANumber(seq);

  const operator = await prisma.user.findUnique({ where: { id: input.userId } });
  const machine = input.machineId
    ? await prisma.machine.findUnique({ where: { id: input.machineId } })
    : null;

  const capa = await prisma.cAPA.create({
    data: {
      companyId: input.companyId,
      capaNumber,
      title: `${cfg.titlePrefix} — ${operator?.name ?? 'Operator'}${machine ? ` (${machine.name})` : ''}`,
      description:
        input.details.description ??
        `Auto-generated CAPA triggered by ${input.trigger} for ${operator?.name ?? 'operator'}.`,
      severity,
      status: 'OPEN',
      deviationType: cfg.deviationType,
      ownerId,
      machineId: input.machineId ?? undefined,
      dueDate: addDays(new Date(), dueDays),
      autoGenerated: true,
      triggerReason: input.trigger,
      ...(input.details.trainingRecordId
        ? { trainingRecords: { connect: { id: input.details.trainingRecordId } } }
        : {}),
    },
  });

  await logAction({
    userId: input.userId,
    action: 'CREATE',
    entityType: 'CAPA',
    entityId: capa.id,
    newValue: { capaNumber, trigger: input.trigger, severity },
    changeReason: `Auto-generated: ${input.trigger}`,
    capaId: capa.id,
  });

  const owner = await prisma.user.findUnique({ where: { id: ownerId } });
  if (owner) {
    await sendCAPAAssignment(owner, {
      capaNumber: capa.capaNumber,
      title: capa.title,
      severity: capa.severity,
      dueDate: capa.dueDate,
    });
  }

  return capa;
}

export async function updateCAPAStatus(
  capaId: string,
  newStatus: CAPAStatus,
  userId: string,
  comments?: string
) {
  const existing = await prisma.cAPA.findUnique({ where: { id: capaId } });
  if (!existing) throw new Error('CAPA not found');

  const data: Record<string, unknown> = { status: newStatus };
  if (newStatus === 'CLOSED') data.closedAt = new Date();

  const updated = await prisma.cAPA.update({
    where: { id: capaId },
    data,
  });

  await logAction({
    userId,
    action: 'STATUS_CHANGE',
    entityType: 'CAPA',
    entityId: capaId,
    oldValue: { status: existing.status },
    newValue: { status: newStatus },
    changeReason: comments ?? `Status → ${newStatus}`,
    capaId,
  });

  return updated;
}

/**
 * Effectiveness check: for training-related CAPAs, did the operator pass the
 * related training within 30 days of closure? If not, reopen with escalation.
 */
export async function checkCAPAEffectiveness(capaId: string): Promise<boolean> {
  const capa = await prisma.cAPA.findUnique({
    where: { id: capaId },
    include: { trainingRecords: true },
  });
  if (!capa || capa.status !== 'CLOSED' || !capa.closedAt) return false;

  const windowStart = capa.closedAt;
  const windowEnd = addDays(capa.closedAt, 30);

  const passed = await prisma.trainingRecord.findFirst({
    where: {
      capaId,
      status: 'COMPLETED',
      completedAt: { gte: windowStart, lte: windowEnd },
    },
  });

  const effective = Boolean(passed);
  await prisma.cAPA.update({
    where: { id: capaId },
    data: {
      effectivenessCheck: effective ? 'Effective — operator passed within 30 days' : 'Ineffective — reopened',
      effectivenessDate: new Date(),
      ...(effective ? {} : { status: 'OPEN' }),
    },
  });

  if (!effective) {
    await logAction({
      action: 'REOPEN',
      entityType: 'CAPA',
      entityId: capaId,
      changeReason: 'Effectiveness check failed — operator did not pass within 30 days',
      capaId,
    });
  }
  return effective;
}

export async function getOverdueCAPAs(companyId?: string) {
  const now = new Date();
  return prisma.cAPA.findMany({
    where: {
      ...(companyId ? { companyId } : {}),
      status: { notIn: ['CLOSED'] },
      dueDate: { lt: now },
    },
    include: { owner: { select: { name: true, email: true } }, machine: { select: { name: true } } },
    orderBy: { dueDate: 'asc' },
  });
}

/** Mark past-due open CAPAs as OVERDUE. */
export async function flagOverdueCAPAs(): Promise<number> {
  const now = new Date();
  const res = await prisma.cAPA.updateMany({
    where: {
      status: { notIn: ['CLOSED', 'OVERDUE'] },
      dueDate: { lt: now },
    },
    data: { status: 'OVERDUE' },
  });
  return res.count;
}
