import type { CAPASeverity, CAPAStatus, DeviationType, Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';
import { requireUser, requireRole, handle, ApiError } from '@/lib/api-helpers';
import { MANAGER_ROLES, isManager } from '@/lib/auth';
import { logAction } from '@/lib/audit-logger';
import { getClientIp, generateCAPANumber } from '@/lib/utils';
import { sendCAPAAssignment } from '@/lib/email-service';

const SEVERITIES: CAPASeverity[] = ['MINOR', 'MAJOR', 'CRITICAL'];
const STATUSES: CAPAStatus[] = [
  'OPEN',
  'INVESTIGATION',
  'ACTION_TAKEN',
  'VERIFICATION',
  'CLOSED',
  'OVERDUE',
];
const DEVIATION_TYPES: DeviationType[] = [
  'WEIGHT_VARIATION',
  'EQUIPMENT_FAILURE',
  'DOCUMENTATION_ERROR',
  'PROCESS_DEVIATION',
  'ENVIRONMENTAL',
  'PERSONNEL',
  'OTHER',
];

/** Serialized CAPA row for list/board views. */
export interface CAPAListItem {
  id: string;
  capaNumber: string;
  title: string;
  description: string;
  severity: CAPASeverity;
  status: CAPAStatus;
  deviationType: DeviationType;
  dueDate: string;
  closedAt: string | null;
  createdAt: string;
  autoGenerated: boolean;
  triggerReason: string | null;
  ownerId: string;
  ownerName: string;
  machineId: string | null;
  machineName: string | null;
}

export interface CAPAListResponse {
  capas: CAPAListItem[];
  canManage: boolean;
  currentUserId: string;
}

/** GET /api/capa — list CAPAs for the caller's company. */
export async function GET(req: Request) {
  return handle(async (): Promise<CAPAListResponse> => {
    const user = await requireUser();
    const { searchParams } = new URL(req.url);

    const statusParam = searchParams.get('status');
    const severityParam = searchParams.get('severity');
    const machineIdParam = searchParams.get('machineId');

    const where: Prisma.CAPAWhereInput = { companyId: user.companyId };
    if (statusParam && STATUSES.includes(statusParam as CAPAStatus)) {
      where.status = statusParam as CAPAStatus;
    }
    if (severityParam && SEVERITIES.includes(severityParam as CAPASeverity)) {
      where.severity = severityParam as CAPASeverity;
    }
    if (machineIdParam) {
      where.machineId = machineIdParam;
    }

    const rows = await prisma.cAPA.findMany({
      where,
      include: {
        owner: { select: { id: true, name: true } },
        machine: { select: { id: true, name: true } },
      },
      orderBy: [{ dueDate: 'asc' }, { createdAt: 'desc' }],
    });

    const capas: CAPAListItem[] = rows.map((c) => ({
      id: c.id,
      capaNumber: c.capaNumber,
      title: c.title,
      description: c.description,
      severity: c.severity,
      status: c.status,
      deviationType: c.deviationType,
      dueDate: c.dueDate.toISOString(),
      closedAt: c.closedAt ? c.closedAt.toISOString() : null,
      createdAt: c.createdAt.toISOString(),
      autoGenerated: c.autoGenerated,
      triggerReason: c.triggerReason,
      ownerId: c.ownerId,
      ownerName: c.owner.name,
      machineId: c.machineId,
      machineName: c.machine?.name ?? null,
    }));

    return { capas, canManage: isManager(user.role), currentUserId: user.id };
  });
}

interface CreateCAPABody {
  title?: string;
  description?: string;
  severity?: string;
  deviationType?: string;
  machineId?: string | null;
  ownerId?: string;
  dueDate?: string;
  immediateAction?: string | null;
  rootCause?: string | null;
  preventiveAction?: string | null;
}

/** Compute the next available CAPA sequence number for today (globally unique). */
async function nextCapaNumber(): Promise<string> {
  const start = new Date();
  start.setHours(0, 0, 0, 0);
  const count = await prisma.cAPA.count({ where: { createdAt: { gte: start } } });
  let seq = count + 1;
  for (let i = 0; i < 10; i++) {
    const candidate = generateCAPANumber(seq);
    const clash = await prisma.cAPA.findUnique({ where: { capaNumber: candidate } });
    if (!clash) return candidate;
    seq++;
  }
  // Extremely unlikely fallback — timestamp suffix guarantees uniqueness.
  return `${generateCAPANumber(seq)}-${Date.now().toString().slice(-4)}`;
}

/** POST /api/capa — manual CAPA creation (managers only). */
export async function POST(req: Request) {
  return handle(async () => {
    const user = await requireRole(MANAGER_ROLES);
    const body = (await req.json().catch(() => null)) as CreateCAPABody | null;
    if (!body) throw new ApiError('Invalid request body', 400);

    const title = body.title?.trim();
    const description = body.description?.trim();
    if (!title) throw new ApiError('Title is required', 422);
    if (!description) throw new ApiError('Description is required', 422);

    if (!body.severity || !SEVERITIES.includes(body.severity as CAPASeverity)) {
      throw new ApiError('A valid severity is required', 422);
    }
    if (!body.deviationType || !DEVIATION_TYPES.includes(body.deviationType as DeviationType)) {
      throw new ApiError('A valid deviation type is required', 422);
    }
    const severity = body.severity as CAPASeverity;
    const deviationType = body.deviationType as DeviationType;

    if (!body.ownerId) throw new ApiError('An owner is required', 422);
    const owner = await prisma.user.findFirst({
      where: { id: body.ownerId, companyId: user.companyId },
    });
    if (!owner) throw new ApiError('Owner not found in your company', 422);

    let machineId: string | null = null;
    if (body.machineId) {
      const machine = await prisma.machine.findFirst({
        where: { id: body.machineId, companyId: user.companyId },
        select: { id: true },
      });
      if (!machine) throw new ApiError('Machine not found in your company', 422);
      machineId = machine.id;
    }

    if (!body.dueDate) throw new ApiError('A due date is required', 422);
    const dueDate = new Date(body.dueDate);
    if (Number.isNaN(dueDate.getTime())) throw new ApiError('Invalid due date', 422);

    const capaNumber = await nextCapaNumber();

    const capa = await prisma.cAPA.create({
      data: {
        companyId: user.companyId,
        capaNumber,
        title,
        description,
        severity,
        status: 'OPEN',
        deviationType,
        ownerId: owner.id,
        machineId: machineId ?? undefined,
        dueDate,
        immediateAction: body.immediateAction?.trim() || undefined,
        rootCause: body.rootCause?.trim() || undefined,
        preventiveAction: body.preventiveAction?.trim() || undefined,
        autoGenerated: false,
      },
    });

    await logAction({
      userId: user.id,
      action: 'CREATE',
      entityType: 'CAPA',
      entityId: capa.id,
      newValue: {
        capaNumber: capa.capaNumber,
        title: capa.title,
        severity: capa.severity,
        deviationType: capa.deviationType,
        ownerId: capa.ownerId,
      },
      changeReason: 'Manual CAPA created',
      ipAddress: getClientIp(req.headers),
      capaId: capa.id,
    });

    await sendCAPAAssignment(owner, {
      capaNumber: capa.capaNumber,
      title: capa.title,
      severity: capa.severity,
      dueDate: capa.dueDate,
    });

    return { capa };
  });
}
